spring.application.name=Petcare
server.port=8080

# ===============================
# DATABASE - MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/Petcare?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pet2345.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOGGING (opcional para debug)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# EMAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=petcare.demo.app@gmail.com
spring.mail.password=passwordFalso123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
